apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/scc: node-exporter
    creationTimestamp: "2022-05-13T05:51:09Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:containers:
            k:{"name":"server"}:
              .: {}
              f:command: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources: {}
              f:securityContext:
                .: {}
                f:privileged: {}
                f:runAsUser: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:hostNetwork: {}
          f:hostPID: {}
          f:nodeName: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext: {}
          f:terminationGracePeriodSeconds: {}
      manager: oc
      operation: Update
      time: "2022-05-13T05:51:08Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            .: {}
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"PodScheduled"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.44.134.239"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      manager: kubelet
      operation: Update
      time: "2022-05-13T05:51:22Z"
    name: iperf-13may22-095050-server
    namespace: iperf-test
    resourceVersion: "20287087"
    uid: 5b82df74-6418-4587-b92b-2fbe67ca6a8b
  spec:
    containers:
    - command:
      - bash
      - -c
      - |
        if [ -z "10.44.134.239" ]; then LIP=$(ip address show dev  | grep -w -m1 "inet" | sed 's/\s*inet\s*\([0-9.]*\)\/.*/\1/'); fi
        if [ -n "10.44.134.239" ]; then LIP="10.44.134.239"; fi
        if [ -z "${LIP}" ]; then echo "Failed to determine IP of "; exit 1; fi
        echo "${LIP}" | tee /tmp/IP
        iperf3 -i 5 -s --one-off -B ${LIP}
      image: quay.io/kxr/iperf3
      imagePullPolicy: IfNotPresent
      name: server
      resources: {}
      securityContext:
        privileged: true
        runAsUser: 0
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-tss6b
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostNetwork: true
    hostPID: true
    imagePullSecrets:
    - name: default-dockercfg-vd4np
    nodeName: sharedocp48-f9w4j-master-0
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-tss6b
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-05-13T05:51:09Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-05-13T05:51:22Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-05-13T05:51:22Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-05-13T05:51:09Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://38c653f6be51b1a20f11307e6b6bc2ac2bdd87522ff760d1179228b9339c53bb
      image: quay.io/kxr/iperf3:latest
      imageID: quay.io/kxr/iperf3@sha256:93b32a4b8ed93fe0efab7bc35fa9ed88d8288d628804de69a837c6434d9f4afb
      lastState: {}
      name: server
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-05-13T05:51:21Z"
    hostIP: 10.44.134.239
    phase: Running
    podIP: 10.44.134.239
    podIPs:
    - ip: 10.44.134.239
    qosClass: BestEffort
    startTime: "2022-05-13T05:51:09Z"
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/scc: node-exporter
    creationTimestamp: "2022-05-13T05:51:32Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:containers:
            k:{"name":"client"}:
              .: {}
              f:command: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources: {}
              f:securityContext:
                .: {}
                f:privileged: {}
                f:runAsUser: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:hostNetwork: {}
          f:hostPID: {}
          f:nodeName: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext: {}
          f:terminationGracePeriodSeconds: {}
      manager: oc
      operation: Update
      time: "2022-05-13T05:51:32Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            .: {}
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"PodScheduled"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.44.134.170"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      manager: kubelet
      operation: Update
      time: "2022-05-13T05:52:37Z"
    name: iperf-13may22-095050-client
    namespace: iperf-test
    resourceVersion: "20287583"
    uid: f03742dd-79d4-4ff0-851a-c406745a79db
  spec:
    containers:
    - command:
      - bash
      - -c
      - |
        iperf3 -i 5 -t 60  --forceflush -c 10.44.134.239
        exit 0
      image: quay.io/kxr/iperf3
      imagePullPolicy: IfNotPresent
      name: client
      resources: {}
      securityContext:
        privileged: true
        runAsUser: 0
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-pn5hs
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostNetwork: true
    hostPID: true
    imagePullSecrets:
    - name: default-dockercfg-vd4np
    nodeName: sharedocp48-f9w4j-worker-gq96m
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-pn5hs
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-05-13T05:51:32Z"
      reason: PodCompleted
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-05-13T05:52:37Z"
      reason: PodCompleted
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-05-13T05:52:37Z"
      reason: PodCompleted
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-05-13T05:51:32Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://18c4d16934f85e506c09a8350b72594bd772dd1ac30eb17cd4c6e6e0425130e0
      image: quay.io/kxr/iperf3:latest
      imageID: quay.io/kxr/iperf3@sha256:93b32a4b8ed93fe0efab7bc35fa9ed88d8288d628804de69a837c6434d9f4afb
      lastState: {}
      name: client
      ready: false
      restartCount: 0
      started: false
      state:
        terminated:
          containerID: cri-o://18c4d16934f85e506c09a8350b72594bd772dd1ac30eb17cd4c6e6e0425130e0
          exitCode: 0
          finishedAt: "2022-05-13T05:52:36Z"
          reason: Completed
          startedAt: "2022-05-13T05:51:35Z"
    hostIP: 10.44.134.170
    phase: Succeeded
    podIP: 10.44.134.170
    podIPs:
    - ip: 10.44.134.170
    qosClass: BestEffort
    startTime: "2022-05-13T05:51:32Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
