apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/scc: node-exporter
    creationTimestamp: "2022-05-13T04:00:20Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:containers:
            k:{"name":"server"}:
              .: {}
              f:command: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources: {}
              f:securityContext:
                .: {}
                f:privileged: {}
                f:runAsUser: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:hostNetwork: {}
          f:hostPID: {}
          f:nodeName: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext: {}
          f:terminationGracePeriodSeconds: {}
      manager: oc
      operation: Update
      time: "2022-05-13T04:00:20Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            .: {}
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"PodScheduled"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.44.134.239"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      manager: kubelet
      operation: Update
      time: "2022-05-13T04:01:46Z"
    name: iperf-13may22-075959-server
    namespace: iperf-test
    resourceVersion: "20240868"
    uid: 9b5dec6e-7108-4e5b-b9fb-a9e6a678477f
  spec:
    containers:
    - command:
      - bash
      - -c
      - |
        if [ -z "10.44.134.239" ]; then LIP=$(ip address show dev  | grep -w -m1 "inet" | sed 's/\s*inet\s*\([0-9.]*\)\/.*/\1/'); fi
        if [ -n "10.44.134.239" ]; then LIP="10.44.134.239"; fi
        if [ -z "${LIP}" ]; then echo "Failed to determine IP of "; exit 1; fi
        echo "${LIP}" | tee /tmp/IP
        iperf3 -i 5 -s --one-off -B ${LIP}
      image: quay.io/kxr/iperf3
      imagePullPolicy: IfNotPresent
      name: server
      resources: {}
      securityContext:
        privileged: true
        runAsUser: 0
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-wtfvq
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostNetwork: true
    hostPID: true
    imagePullSecrets:
    - name: default-dockercfg-vd4np
    nodeName: sharedocp48-f9w4j-master-0
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-wtfvq
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-05-13T04:00:20Z"
      reason: PodCompleted
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-05-13T04:01:46Z"
      reason: PodCompleted
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-05-13T04:01:46Z"
      reason: PodCompleted
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-05-13T04:00:20Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://ba51208ec1b553cb0d7971a51404b4993660bcaaf4c5e5044c177afce621a141
      image: quay.io/kxr/iperf3:latest
      imageID: quay.io/kxr/iperf3@sha256:93b32a4b8ed93fe0efab7bc35fa9ed88d8288d628804de69a837c6434d9f4afb
      lastState: {}
      name: server
      ready: false
      restartCount: 0
      started: false
      state:
        terminated:
          containerID: cri-o://ba51208ec1b553cb0d7971a51404b4993660bcaaf4c5e5044c177afce621a141
          exitCode: 0
          finishedAt: "2022-05-13T04:01:44Z"
          reason: Completed
          startedAt: "2022-05-13T04:00:30Z"
    hostIP: 10.44.134.239
    phase: Succeeded
    podIP: 10.44.134.239
    podIPs:
    - ip: 10.44.134.239
    qosClass: BestEffort
    startTime: "2022-05-13T04:00:20Z"
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/scc: node-exporter
    creationTimestamp: "2022-05-13T04:00:41Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:containers:
            k:{"name":"client"}:
              .: {}
              f:command: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources: {}
              f:securityContext:
                .: {}
                f:privileged: {}
                f:runAsUser: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:hostNetwork: {}
          f:hostPID: {}
          f:nodeName: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext: {}
          f:terminationGracePeriodSeconds: {}
      manager: oc
      operation: Update
      time: "2022-05-13T04:00:41Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            .: {}
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"PodScheduled"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.44.134.170"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      manager: kubelet
      operation: Update
      time: "2022-05-13T04:01:45Z"
    name: iperf-13may22-075959-client
    namespace: iperf-test
    resourceVersion: "20240855"
    uid: b68866d5-f356-48a4-93a3-24bde49f7e3b
  spec:
    containers:
    - command:
      - bash
      - -c
      - |
        iperf3 -i 5 -t 60  --forceflush -c 10.44.134.239
        exit 0
      image: quay.io/kxr/iperf3
      imagePullPolicy: IfNotPresent
      name: client
      resources: {}
      securityContext:
        privileged: true
        runAsUser: 0
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-qgrht
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostNetwork: true
    hostPID: true
    imagePullSecrets:
    - name: default-dockercfg-vd4np
    nodeName: sharedocp48-f9w4j-worker-gq96m
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-qgrht
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-05-13T04:00:42Z"
      reason: PodCompleted
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-05-13T04:01:45Z"
      reason: PodCompleted
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-05-13T04:01:45Z"
      reason: PodCompleted
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-05-13T04:00:42Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://db443e30ddb0fe7378e28bbbc9e66b8bc02e761d0fdac1df4f991247804a8448
      image: quay.io/kxr/iperf3:latest
      imageID: quay.io/kxr/iperf3@sha256:93b32a4b8ed93fe0efab7bc35fa9ed88d8288d628804de69a837c6434d9f4afb
      lastState: {}
      name: client
      ready: false
      restartCount: 0
      started: false
      state:
        terminated:
          containerID: cri-o://db443e30ddb0fe7378e28bbbc9e66b8bc02e761d0fdac1df4f991247804a8448
          exitCode: 0
          finishedAt: "2022-05-13T04:01:44Z"
          reason: Completed
          startedAt: "2022-05-13T04:00:43Z"
    hostIP: 10.44.134.170
    phase: Succeeded
    podIP: 10.44.134.170
    podIPs:
    - ip: 10.44.134.170
    qosClass: BestEffort
    startTime: "2022-05-13T04:00:42Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
