apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/network-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.129.0.44"
            ],
            "default": true,
            "dns": {}
        }]
      k8s.v1.cni.cncf.io/networks-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.129.0.44"
            ],
            "default": true,
            "dns": {}
        }]
      openshift.io/scc: node-exporter
    creationTimestamp: "2022-05-12T17:19:45Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:containers:
            k:{"name":"server"}:
              .: {}
              f:command: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources: {}
              f:securityContext:
                .: {}
                f:privileged: {}
                f:runAsUser: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:hostPID: {}
          f:nodeName: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext: {}
          f:terminationGracePeriodSeconds: {}
      manager: oc
      operation: Update
      time: "2022-05-12T17:19:45Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:k8s.v1.cni.cncf.io/network-status: {}
            f:k8s.v1.cni.cncf.io/networks-status: {}
      manager: multus
      operation: Update
      time: "2022-05-12T17:19:52Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            .: {}
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"PodScheduled"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.129.0.44"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      manager: kubelet
      operation: Update
      time: "2022-05-12T17:21:33Z"
    name: iperf-12may22-211926-server
    namespace: iperf-test
    resourceVersion: "19968169"
    uid: 6a084e55-adad-4366-8928-884910954eaa
  spec:
    containers:
    - command:
      - bash
      - -c
      - |
        if [ -z "" ]; then LIP=$(ip address show dev eth0 | grep -w -m1 "inet" | sed 's/\s*inet\s*\([0-9.]*\)\/.*/\1/'); fi
        if [ -n "" ]; then LIP=""; fi
        if [ -z "${LIP}" ]; then echo "Failed to determine IP of eth0"; exit 1; fi
        echo "${LIP}" | tee /tmp/IP
        iperf3 -i 5 -s --one-off -B ${LIP}
      image: quay.io/kxr/iperf3
      imagePullPolicy: IfNotPresent
      name: server
      resources: {}
      securityContext:
        privileged: true
        runAsUser: 0
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-ppjjm
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostPID: true
    imagePullSecrets:
    - name: default-dockercfg-vd4np
    nodeName: sharedocp48-f9w4j-master-0
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-ppjjm
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-05-12T17:19:46Z"
      reason: PodCompleted
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-05-12T17:21:33Z"
      reason: PodCompleted
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-05-12T17:21:33Z"
      reason: PodCompleted
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-05-12T17:19:46Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://e12a6c65e851a19be6fa9f2ba6c8e1f8c7d3dd31275fe8ac2469a7834c545323
      image: quay.io/kxr/iperf3:latest
      imageID: quay.io/kxr/iperf3@sha256:93b32a4b8ed93fe0efab7bc35fa9ed88d8288d628804de69a837c6434d9f4afb
      lastState: {}
      name: server
      ready: false
      restartCount: 0
      started: false
      state:
        terminated:
          containerID: cri-o://e12a6c65e851a19be6fa9f2ba6c8e1f8c7d3dd31275fe8ac2469a7834c545323
          exitCode: 0
          finishedAt: "2022-05-12T17:21:32Z"
          reason: Completed
          startedAt: "2022-05-12T17:20:11Z"
    hostIP: 10.44.134.239
    phase: Succeeded
    podIP: 10.129.0.44
    podIPs:
    - ip: 10.129.0.44
    qosClass: BestEffort
    startTime: "2022-05-12T17:19:46Z"
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/network-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.130.0.31"
            ],
            "default": true,
            "dns": {}
        }]
      k8s.v1.cni.cncf.io/networks-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.130.0.31"
            ],
            "default": true,
            "dns": {}
        }]
      openshift.io/scc: node-exporter
    creationTimestamp: "2022-05-12T17:20:27Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:containers:
            k:{"name":"client"}:
              .: {}
              f:command: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources: {}
              f:securityContext:
                .: {}
                f:privileged: {}
                f:runAsUser: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:hostPID: {}
          f:nodeName: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext: {}
          f:terminationGracePeriodSeconds: {}
      manager: oc
      operation: Update
      time: "2022-05-12T17:20:27Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:k8s.v1.cni.cncf.io/network-status: {}
            f:k8s.v1.cni.cncf.io/networks-status: {}
      manager: multus
      operation: Update
      time: "2022-05-12T17:20:29Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            .: {}
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"PodScheduled"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.130.0.31"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      manager: kubelet
      operation: Update
      time: "2022-05-12T17:21:32Z"
    name: iperf-12may22-211926-client
    namespace: iperf-test
    resourceVersion: "19968160"
    uid: 7ae47097-4ec1-48ed-972b-73e14d35f7b5
  spec:
    containers:
    - command:
      - bash
      - -c
      - |
        iperf3 -i 5 -t 60  --forceflush -c 10.129.0.44
        exit 0
      image: quay.io/kxr/iperf3
      imagePullPolicy: IfNotPresent
      name: client
      resources: {}
      securityContext:
        privileged: true
        runAsUser: 0
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-t8b6q
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostPID: true
    imagePullSecrets:
    - name: default-dockercfg-vd4np
    nodeName: sharedocp48-f9w4j-worker-gq96m
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-t8b6q
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-05-12T17:20:27Z"
      reason: PodCompleted
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-05-12T17:21:32Z"
      reason: PodCompleted
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-05-12T17:21:32Z"
      reason: PodCompleted
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-05-12T17:20:27Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://f3603c07084cc330426398636124ec0c2d007df81efe1f051eb5ebb7f8d978fb
      image: quay.io/kxr/iperf3:latest
      imageID: quay.io/kxr/iperf3@sha256:93b32a4b8ed93fe0efab7bc35fa9ed88d8288d628804de69a837c6434d9f4afb
      lastState: {}
      name: client
      ready: false
      restartCount: 0
      started: false
      state:
        terminated:
          containerID: cri-o://f3603c07084cc330426398636124ec0c2d007df81efe1f051eb5ebb7f8d978fb
          exitCode: 0
          finishedAt: "2022-05-12T17:21:32Z"
          reason: Completed
          startedAt: "2022-05-12T17:20:31Z"
    hostIP: 10.44.134.170
    phase: Succeeded
    podIP: 10.130.0.31
    podIPs:
    - ip: 10.130.0.31
    qosClass: BestEffort
    startTime: "2022-05-12T17:20:27Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
