apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/scc: node-exporter
    creationTimestamp: "2022-05-12T17:43:18Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:containers:
            k:{"name":"server"}:
              .: {}
              f:command: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources: {}
              f:securityContext:
                .: {}
                f:privileged: {}
                f:runAsUser: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:hostNetwork: {}
          f:hostPID: {}
          f:nodeName: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext: {}
          f:terminationGracePeriodSeconds: {}
      manager: oc
      operation: Update
      time: "2022-05-12T17:43:18Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            .: {}
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"PodScheduled"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.44.134.239"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      manager: kubelet
      operation: Update
      time: "2022-05-12T17:44:42Z"
    name: iperf-12may22-214259-server
    namespace: iperf-test
    resourceVersion: "19977699"
    uid: 04ee5b7c-c5c3-41ce-a289-2191e2b36972
  spec:
    containers:
    - command:
      - bash
      - -c
      - |
        if [ -z "10.44.134.239" ]; then LIP=$(ip address show dev  | grep -w -m1 "inet" | sed 's/\s*inet\s*\([0-9.]*\)\/.*/\1/'); fi
        if [ -n "10.44.134.239" ]; then LIP="10.44.134.239"; fi
        if [ -z "${LIP}" ]; then echo "Failed to determine IP of "; exit 1; fi
        echo "${LIP}" | tee /tmp/IP
        iperf3 -i 5 -s --one-off -B ${LIP}
      image: quay.io/kxr/iperf3
      imagePullPolicy: IfNotPresent
      name: server
      resources: {}
      securityContext:
        privileged: true
        runAsUser: 0
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-j7kft
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostNetwork: true
    hostPID: true
    imagePullSecrets:
    - name: default-dockercfg-vd4np
    nodeName: sharedocp48-f9w4j-master-0
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-j7kft
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-05-12T17:43:18Z"
      reason: PodCompleted
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-05-12T17:44:42Z"
      reason: PodCompleted
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-05-12T17:44:42Z"
      reason: PodCompleted
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-05-12T17:43:18Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://63c2176ed4714619f1914000ac3f98be4e99fc256191faf2d8ae006055f41b2d
      image: quay.io/kxr/iperf3:latest
      imageID: quay.io/kxr/iperf3@sha256:93b32a4b8ed93fe0efab7bc35fa9ed88d8288d628804de69a837c6434d9f4afb
      lastState: {}
      name: server
      ready: false
      restartCount: 0
      started: false
      state:
        terminated:
          containerID: cri-o://63c2176ed4714619f1914000ac3f98be4e99fc256191faf2d8ae006055f41b2d
          exitCode: 0
          finishedAt: "2022-05-12T17:44:42Z"
          reason: Completed
          startedAt: "2022-05-12T17:43:26Z"
    hostIP: 10.44.134.239
    phase: Succeeded
    podIP: 10.44.134.239
    podIPs:
    - ip: 10.44.134.239
    qosClass: BestEffort
    startTime: "2022-05-12T17:43:18Z"
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/scc: node-exporter
    creationTimestamp: "2022-05-12T17:43:39Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:containers:
            k:{"name":"client"}:
              .: {}
              f:command: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources: {}
              f:securityContext:
                .: {}
                f:privileged: {}
                f:runAsUser: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:hostNetwork: {}
          f:hostPID: {}
          f:nodeName: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext: {}
          f:terminationGracePeriodSeconds: {}
      manager: oc
      operation: Update
      time: "2022-05-12T17:43:39Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            .: {}
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"PodScheduled"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.44.134.170"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      manager: kubelet
      operation: Update
      time: "2022-05-12T17:44:42Z"
    name: iperf-12may22-214259-client
    namespace: iperf-test
    resourceVersion: "19977698"
    uid: 7f6f84bd-6b38-40a7-a223-589ae3c06f0c
  spec:
    containers:
    - command:
      - bash
      - -c
      - |
        iperf3 -i 5 -t 60  --forceflush -c 10.44.134.239
        exit 0
      image: quay.io/kxr/iperf3
      imagePullPolicy: IfNotPresent
      name: client
      resources: {}
      securityContext:
        privileged: true
        runAsUser: 0
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-9z5nx
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostNetwork: true
    hostPID: true
    imagePullSecrets:
    - name: default-dockercfg-vd4np
    nodeName: sharedocp48-f9w4j-worker-gq96m
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-9z5nx
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-05-12T17:43:39Z"
      reason: PodCompleted
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-05-12T17:44:42Z"
      reason: PodCompleted
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-05-12T17:44:42Z"
      reason: PodCompleted
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-05-12T17:43:39Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://25a73e56fa584adf911abce620a1912d3bf90c05c137cfeb3483d884ca4d8509
      image: quay.io/kxr/iperf3:latest
      imageID: quay.io/kxr/iperf3@sha256:93b32a4b8ed93fe0efab7bc35fa9ed88d8288d628804de69a837c6434d9f4afb
      lastState: {}
      name: client
      ready: false
      restartCount: 0
      started: false
      state:
        terminated:
          containerID: cri-o://25a73e56fa584adf911abce620a1912d3bf90c05c137cfeb3483d884ca4d8509
          exitCode: 0
          finishedAt: "2022-05-12T17:44:41Z"
          reason: Completed
          startedAt: "2022-05-12T17:43:41Z"
    hostIP: 10.44.134.170
    phase: Succeeded
    podIP: 10.44.134.170
    podIPs:
    - ip: 10.44.134.170
    qosClass: BestEffort
    startTime: "2022-05-12T17:43:39Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
